2023-07-12 22:23:22,786 : INFO : root : Loading config.
2023-07-12 22:23:22,789 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-07-12 22:23:22,789 : INFO : ConfigProcessor : Loading config from cache: C:\Users\warzz\AppData\Local\Temp\c7ddc35c564c409ccec16ce42249e5f8.mpf_cache
2023-07-12 22:23:22,795 : WARNING : ConfigProcessor : Config file in cache changed: d:\MPF\springbreak\config\devices.yaml
2023-07-12 22:23:22,795 : INFO : ConfigProcessor : Loading config from file C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\mpfconfig.yaml.
2023-07-12 22:23:22,849 : INFO : ConfigProcessor : Loading config: C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\mpfconfig.yaml
2023-07-12 22:23:22,850 : INFO : ConfigProcessor : Loading config from file d:\MPF\springbreak\config\config.yaml.
2023-07-12 22:23:22,853 : INFO : ConfigProcessor : Loading config: d:\MPF\springbreak\config\config.yaml
2023-07-12 22:23:22,859 : INFO : ConfigProcessor : Loading config: d:\MPF\springbreak\config\coils.yaml
2023-07-12 22:23:22,863 : INFO : ConfigProcessor : Loading config: d:\MPF\springbreak\config\switches.yaml
2023-07-12 22:23:22,871 : INFO : ConfigProcessor : Loading config: d:\MPF\springbreak\config\devices.yaml
2023-07-12 22:23:22,873 : INFO : ConfigProcessor : Loading config: d:\MPF\springbreak\config\displays.yaml
2023-07-12 22:23:22,875 : INFO : ConfigProcessor : Loading config: d:\MPF\springbreak\config\keyboard.yaml
2023-07-12 22:23:22,876 : INFO : ConfigProcessor : Config file cache created: C:\Users\warzz\AppData\Local\Temp\c7ddc35c564c409ccec16ce42249e5f8.mpf_cache
2023-07-12 22:23:22,940 : INFO : ConfigProcessor : Loading config from cache: C:\Users\warzz\AppData\Local\Temp\b77c3901e90ec7d7cc601651512a0021.mpf_cache
2023-07-12 22:23:22,941 : INFO : ConfigProcessor : Loading config from cache: C:\Users\warzz\AppData\Local\Temp\a5b2fce8b210d64acc95275c2c9a2339.mpf_cache
2023-07-12 22:23:22,942 : INFO : Machine : Mission Pinball Framework Core Engine v0.56.0
2023-07-12 22:23:22,942 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2023-07-12-22-23-22-mpf-DESKTOP-VQ7DOMB.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-07-12 22:23:22,942 : INFO : Machine : MPF path: C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf
2023-07-12 22:23:22,942 : INFO : Machine : Machine path: d:\MPF\springbreak
2023-07-12 22:23:22,942 : INFO : Machine : Platform: win32
2023-07-12 22:23:22,942 : INFO : Machine : Python executable location: C:\Users\warzz\AppData\Local\Programs\Python\Python39\python.exe
2023-07-12 22:23:22,942 : INFO : Machine : Python version: 3.9.13 (64-bit)
2023-07-12 22:23:22,943 : INFO : Machine : Initialise MPF.
2023-07-12 22:23:23,096 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,139 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2023-07-12 22:23:23,139 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-07-12 22:23:23,139 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.56.0', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,139 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.56.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,139 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,148 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,148 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,148 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,148 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,148 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2023-07-12 22:23:23,148 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2023-07-12 22:23:23,160 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2023-07-12 22:23:23,160 : INFO : SwitchController : Found active switch: ('0-0-27', <Platform.SmartVirtual>) <switch.s_drain_detect>
2023-07-12 22:23:23,160 : INFO : SwitchController : Found active switch: ('0-0-26', <Platform.SmartVirtual>) <switch.s_trough_1>
2023-07-12 22:23:23,161 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2023-07-12 22:23:23,163 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2023-07-12 22:23:25,209 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2023-07-12 22:23:25,209 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2023-07-12 22:23:25,215 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-51' coro=<BallDevice._initialize_async() done, defined at C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\ball_device.py:195> exception=ConfigFileError('Cannot use capacity and ball switches.')>
Traceback (most recent call last):
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_drain: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://docs.missionpinball.org/en/0.56/logs/CFE-ball_device-3.html)
2023-07-12 22:23:25,229 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.56.1', 'prev_value': None, 'change': True}
2023-07-12 22:23:25,230 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.56.1 (config_version=5, BCP v1.1,                      Requires MPF API compatibility v0.56.0 or newer)', 'prev_value': None, 'change': True}
2023-07-12 22:23:25,231 : INFO : ball_device.bd_trough : BCH: Initial count: 3
2023-07-12 22:23:25,241 : INFO : ball_device.bd_trough : State: idle
2023-07-12 22:23:25,241 : INFO : Machine : Starting the main run loop.
2023-07-12 22:23:25,242 : INFO : Machine : Shutting down...
2023-07-12 22:23:25,242 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2023-07-12 22:23:25,243 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2023-07-12 22:23:25,244 : INFO : ball_device.bd_plunger : State: idle
2023-07-12 22:23:25,251 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2023-07-12 22:23:25,254 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2023-07-12 22:23:25,254 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\utility_functions.py:759
handle: <Handle Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\utility_functions.py:759>
Traceback (most recent call last):
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\utility_functions.py", line 767, in raise_exceptions
    future.result()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\ball_controller.py", line 90, in _add_new_balls_to_playfield
    self.num_balls_known = await self._count_all_balls_in_devices()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\ball_controller.py", line 129, in _count_all_balls_in_devices
    futures.append(asyncio.ensure_future(device.ball_count_handler.counter.wait_for_count_stable()))
AttributeError: 'NoneType' object has no attribute 'wait_for_count_stable'
2023-07-12 22:23:25,256 : INFO : EventManager : Event: ======'machine_var_audits_events_game_ended'====== Args={'value': 1, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,258 : INFO : EventManager : Event: ======'machine_var_audits_events_game_started'====== Args={'value': 5, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,258 : INFO : EventManager : Event: ======'machine_var_audits_player_score'====== Args={'value': {'average': 0.0, 'top': [0], 'total': 1}, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,259 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_drain_detect'====== Args={'value': 5, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,259 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_flipper_left'====== Args={'value': 3, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,259 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_flipper_right'====== Args={'value': 9, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,260 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_plunger_detect'====== Args={'value': 7, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,260 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_plunger_exit'====== Args={'value': 2, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,260 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_popbumper_1'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,261 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_popbumper_2'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,261 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_popbumper_3'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,262 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_slingshot'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,262 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_start_button'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,262 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_1'====== Args={'value': 6, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,263 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_2'====== Args={'value': 0, 'prev_value': None, 'change': True}
2023-07-12 22:23:25,263 : INFO : EventManager : Event: ======'init_phase_5'====== Args={}
2023-07-12 22:23:26,265 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-1' coro=<MachineController.initialise() done, defined at C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py:244> exception=AttributeError("'NoneType' object has no attribute 'config'")>
Traceback (most recent call last):
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py", line 256, in initialise
    await self._start_platforms()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py", line 338, in _start_platforms
    await hardware_platform.start()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\platforms\smart_virtual.py", line 288, in start
    self._initialise_ball_devices()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\platforms\smart_virtual.py", line 347, in _initialise_ball_devices
    action = device.ejector.config['eject_coil'].hw_driver.action = AddBallToTargetAction(
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\platforms\smart_virtual.py", line 178, in __init__
    self.ball_switches = device.ball_count_handler.counter.config.get('ball_switches', [])
AttributeError: 'NoneType' object has no attribute 'config'
2023-07-12 22:23:26,432 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-79' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py:571> wait_for=<_OverlappedFuture cancelled>>
2023-07-12 22:23:26,434 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_drain: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://docs.missionpinball.org/en/0.56/logs/CFE-ball_device-3.html)
2023-07-12 22:23:29,973 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    raise self._exception['exception']
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\ball_device.py", line 197, in _initialize_async
    await self.ball_count_handler.initialise()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialise
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_drain: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://docs.missionpinball.org/en/0.56/logs/CFE-ball_device-3.html)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\commands\game.py", line 239, in __init__
    self.machine.run()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py", line 693, in run
    self._run_loop()
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\machine.py", line 800, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\warzz\AppData\Local\Programs\Python\Python39\lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
